apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  labels:
    app: dockercat
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
