apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: dockercat
    component: database
spec:
  type: ClusterIP
  selector:
    app: dockercat
    component: database
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
